# NUMPY EXERCISE

## Instruction

In the questions below, where you find ****, you are expected to fill in the missing code. 
Also be aware that the next column after the question provides the answer for comparism, you are therefore advisednot to run this column so as for the answer not to clear off. All discussion on the exercise should be on the group and you are not expected to share answers

### Submission

Complete the Exercise Above and Submit your notebook to the instructor on whatsapp not on the discussion group. Ensure to mention your name and save the file as your name_numpy1.


In [1]:
#import the numpy library below
import numpy as np

Insert the correct method for creating a NumPy array in the place where you have ****.

In [ ]:
arr = np.****([1, 2, 3, 4, 5])
arr

In [5]:
#The Answer is below

array([1, 2, 3, 4, 5])

Insert the correct argument for creating a NumPy array with 2 dimensions.

In [ ]:
arr = np.array([1, 2, 3, 4],****=2)
arr

In [6]:
# insert ---->ndim
#You should get the answer below

array([[1, 2, 3, 4]])

Insert the correct syntax for checking the number of dimension of a NumPy array.

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr.****)

In [7]:
# insert --->ndim
#You should get the answer below

1


Insert the correct syntax for returning evenly spaces numbers over a specified interval and also return an array of 100 element between starting from 1 and stopping at 2

In [ ]:
arr=np.****(****,****,****)
arr

In [8]:
#The answer is below

array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

create a 4 by 4 identity matrix 

In [ ]:
id_mat=

In [9]:
#The answer is below

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

create an array of 2 random samples between 0,1

In [10]:
#The answer should look like what I have below

array([0.79134722, 0.89441292])

Generate an array of zeros to form a 6 by 6 matrix

Generate an array of ones to form a 6 by 6 matrix

create a list of of element 5,7,8,9 and convert the list to an array

What is the difference between rand,randn and randint

Create an array  arr of with 30 element, reshape it into a matrix

## GOODLUCK!!!