In [3]:
#Import your numpy library
import numpy as np

In [6]:
#create a list
my_list=[1,2,3]

In [11]:
my_dict={"a":3,"b":4,"c":5}

In [13]:
my_tuple=(1,2,4,5)

In [17]:
my_scaler=np.array(2)
my_scaler

array(2)

In [20]:
my_vector=np.array(my_list)
my_vector

array([1, 2, 3])

In [21]:
my_vector=np.array([2,3,4,5])

In [22]:
my_vector

array([2, 3, 4, 5])

In [30]:
#matrix
my_mat=np.array([my_vector])
my_mat=np.array([[2,3,4,5]])

In [31]:
my_mat

array([[2, 3, 4, 5]])

In [32]:
my_mat=np.array([[1,2,3],[5,6,7],[8,9,10]])
my_mat

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [33]:
my_mat3=np.array([[1,2],[2,3]])
my_mat3

array([[1, 2],
       [2, 3]])